#! /bin/sh

xset r rate 250 25
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config ~/.config/picom/picom.conf -b &
pgrep -x xwallpaper > /dev/null || xwallpaper --center ~/dotfiles/walls/reze.png

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Chromium desktop='^2'
